services:
  rag-facom:
    build: .
    container_name: motor_rag_facom
    env_file:
      - .env  # Puxa a LIA_API_KEY e os caminhos base do Windows
    environment:
      # --- SOBRESCRITA PARA O LINUX (DOCKER) USANDO CAMINHOS ABSOLUTOS ---
      - PASTA_MD=/app/Documentos/Markdows
      - PASTA_EMBEDDINGS=/app/Documentos/embeddings
      - PASTA_PDF=/app/Documentos/PDFS
      - PASTA_CHUNKS=/app/Documentos/Chunks
    volumes:
      # --- MAPEAMENTO DE PASTAS (Corrigido para a nova raiz) ---
      - ./Documentos:/app/Documentos
      - ./logs:/app/logs
    stdin_open: true  
    tty: true